### ISSUE TITLE
[Bug] Tidal will occasionally HTTPSConnectionPool Read timed out

### ISSUE THREAD

**Issue by motlaghreyhan** [exislow/tidal-dl-ng#94]
### What happened?

Some Tidal requests seems to time out occasionally which kills tidal-dl-ng. Simply re-running the script will generally work to download the file. 

For large batch downloads of many albums, it would be very helpful to have it retry a few times before failing, maybe with a higher wait period in between tracks.

### Version App

latest-master

### What operating system are you seeing the problem on?

None

### Relevant log output

[log.txt](https://github.com/exislow/tidal-dl-ng/files/15051100/log.txt)
(too large for github)

### Your settings

```json
{"skip_existing": "exact", "lyrics_embed": false, "lyrics_file": true, "video_download": false, "download_delay": true, "download_base_path": "/tidal/", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "480", "format_album": "{album_artist}/{album_title} [{album_year}]/CD{track_volume_num}/{album_track_num} - {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "{album_artist}/{album_title} [{album_year}]/CD{track_volume_num}/{album_track_num} - {artist_name} - {track_title}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "", "metadata_cover_dimension": "1280"}
```

**Comment by exislow** [comment]
Thank you for this report. I couldn't reproduce this error so far. Did this happen more often with the same album / other tracks? Are you sure, that you have not had any issues with your internet connection?

I mean, I could implement some retries next to the timeout, but if this was caused due to an error on your side, retries probably wouldn't help...

**Comment by motlaghreyhan** [comment]
I'm not sure about any certain album or track, I've been testing everything with the same beatles abbey road album. I was holding off doing large downloads with your tool until most of my consistent errors went away. Now issue 91 and 92 are fixed, I'll run it some more and see if I run into this issue again.

I really doubt it's my internet, I'm on ethernet with fiber and the connection is good, but I suppose it's possible. tidal-dl never exhibited this, but I've had it happen 2-3 times just while testing with tidal-dl-ng.

**Comment by motlaghreyhan** [comment]
It happened again on the same album [log (1).txt](https://github.com/exislow/tidal-dl-ng/files/15055282/log.1.txt), I tried it again after that (in a clean directory, deleting all previously downloaded files), and it downloaded successfully. I tried another really long max bitrate album [log (2).txt](https://github.com/exislow/tidal-dl-ng/files/15055540/log.2.txt), and failed at some point as well.

**Comment by exislow** [comment]
@thr-4 this is of really no help :-/ Please provide logs and your config.

**Comment by exislow** [comment]
@motlaghreyhan I have downloaded this (https://tidal.com/browse/album/118390427) twice in a row with your config. Still cannot re-produce your error...

**Comment by jessezyl** [comment]
same connection error here, kind of happened frequently.

error logs:
`HTTPSConnectionPool(host='sp-ad-cf.audio.tidal.com', port=443): Max retries exceeded with url: /mediatracks/GikSJzllNTRiMWVkYjBhNWI5NmYyNjEwYWNiZGQ2NzcyMTczXzYxLm1wNCIgHQAAgEAgAioQb7bma1K_nlUQc9gXPmD6ijIFDQAAoEE/27.mp4?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vc3AtYWQtY2YuYXVkaW8udGlkYWwuY29tL21lZGlhdHJhY2tzL0dpa1NKemxsTlRSaU1XVmtZakJoTldJNU5tWXlOakV3WVdOaVpHUTJOemN5TVRjelh6WXhMbTF3TkNJZ0hRQUFnRUFnQWlvUWI3Ym1hMUtfbmxVUWM5Z1hQbUQ2aWpJRkRRQUFvRUUvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxNTAxNDY4NX19fV19&Signature=eOSRekjCHQAKFKdJ0kii4uRBwbXFvGpAYyC1d0HmiSg2Yvlt7ebdWQYpQj~I8IWGEvE3uOsL5a5JagkyZ0O1z0C18wTpuCHZYc410JMObI~eHPZZxUKuPbV6Pcpqy2vKCabPx7nNSlJxieyNqgG9mkK0Jq~z51ph3rODe-0IgmQBbGps76IWh9QZetcubg45nmvVC9Ck2U-aG6p76nIrQSQbhNmtX8Eha10fifxD3v76ua7j~3H7Hpsgl01eViafjJj0nFTxzjNZO1z6k7ijvmU5amXbGEC2fjLTk-kOC6Bn~oC1Q6HsgUAhG9dqjXySYuLVQ1Yk7O1BFhARQso0ag__&Key-Pair-Id=K14LZCZ9QUI4JL (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))`

config:
`{"skip_existing": "exact", "lyrics_embed": false, "lyrics_file": true, "video_download": false, "download_delay": true, "download_base_path": "~/download", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "480", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num} - {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "/usr/local/bin/ffmpeg", "metadata_cover_dimension": "1280", "extract_flac": true, "downgrade_on_hi_res": false}`

kind of doubt that's the "HI_RES_LOSSLESS" config caused, other quality_audio type(like hi_res) doesn't have this error.

hope this is helpful.
